pipeline {
    agent any 
    stages{
        stage("Demo"){
            steps {
                myFunc("Hello from the demo stage!")
            }
        }
    }
}

def myFunc(String myText) {
    echo "myText is set to: ${myText}"
}